<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="dslab.transfer.TransferServerProtocolTest" tests="3" skipped="0" failures="3" errors="0" timestamp="2023-11-14T23:07:11" hostname="Thomass-MacBook-Pro-2.local" time="9.081">
  <properties/>
  <testcase name="tfs_02_sendWithoutData_returnsErrorOnSend" classname="dslab.transfer.TransferServerProtocolTest" time="3.049">
    <failure message="java.lang.AssertionError: &#10;Expected: a string containing &quot;error&quot;&#10;     but: was &quot;no recipients from subject body&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: a string containing &quot;error&quot;
     but: was &quot;no recipients from subject body&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at dslab.JunitSocketClient.assertThat(JunitSocketClient.java:122)
	at dslab.JunitSocketClient.sendAndVerify(JunitSocketClient.java:103)
	at dslab.transfer.TransferServerProtocolTest.tfs_02_sendWithoutData_returnsErrorOnSend(TransferServerProtocolTest.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
</failure>
  </testcase>
  <testcase name="tfs_01_dmtp_simple" classname="dslab.transfer.TransferServerProtocolTest" time="3.014">
    <failure message="java.lang.AssertionError: &#10;Expected: a string containing &quot;ok 1&quot;&#10;     but: was &quot;java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key domain&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: a string containing &quot;ok 1&quot;
     but: was &quot;java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key domain&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at dslab.JunitSocketClient.assertThat(JunitSocketClient.java:122)
	at dslab.JunitSocketClient.sendAndVerify(JunitSocketClient.java:103)
	at dslab.transfer.TransferServerProtocolTest.tfs_01_dmtp_simple(TransferServerProtocolTest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
</failure>
  </testcase>
  <testcase name="tfs_03_sendWithoutRecipient_returnsErrorOnSend" classname="dslab.transfer.TransferServerProtocolTest" time="3.017">
    <failure message="java.lang.AssertionError: &#10;Expected: a string containing &quot;error&quot;&#10;     but: was &quot;no recipients&quot;" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected: a string containing &quot;error&quot;
     but: was &quot;no recipients&quot;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:54)
	at dslab.JunitSocketClient.assertThat(JunitSocketClient.java:120)
	at dslab.JunitSocketClient.sendAndVerify(JunitSocketClient.java:103)
	at dslab.transfer.TransferServerProtocolTest.tfs_03_sendWithoutRecipient_returnsErrorOnSend(TransferServerProtocolTest.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
</failure>
  </testcase>
  <system-out><![CDATA[Test Run Finished: TransferServerProtocolTest
Test Name                                                                        Max Points      Earned Points  
-------------------------------------------------------------------              ----------      ------------   
tfs_03_sendWithoutRecipient_returnsErrorOnSend                                   0,50            0,00           
tfs_01_dmtp_simple                                                               1,50            0,00           
tfs_02_sendWithoutData_returnsErrorOnSend                                        0,50            0,00           
Total points possible: 2.5
Total points earned: 0.0

]]></system-out>
  <system-err><![CDATA[Nov 15, 2023 12:07:11 AM dslab.transfer.TransferServerProtocolTest setUp
INFO: Waiting for server socket to appear
Nov 15, 2023 12:07:14 AM dslab.transfer.TransferServerProtocolTest setUp
INFO: Waiting for server socket to appear
Nov 15, 2023 12:07:17 AM dslab.transfer.TransferServerProtocolTest setUp
INFO: Waiting for server socket to appear
]]></system-err>
</testsuite>
